name: Include your Example.
description: We would be happy for you to give us a example comic you made..
labels: ["create-a-comic", "example"]
assignees: 
  - 
body:      
  - type: textarea
    id: Comic_code
    attributes:
      label: Comic code here, try to use Markdown code formatting
    validations:
      required: true
      
  - type: checkboxes
    id: Copyright_Compliance
    attributes:
      label: Copyright Compliance
      description: Please do not copy works that you are unlicensed to.
      options:
        - label: I consent that this work is either my own work or someone else's work used with permission
          required: true
